-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:b6955474337f5a6b356f91744c9e884a$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "environment@2x.png",
				spriteColorRect = { x = 25, y = 12, width = 908, height = 274 },
				textureRect = { x = 2, y = 110, width = 908, height = 274 },
				spriteSourceSize = { width = 960, height = 300 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player01@2x.png",
				spriteColorRect = { x = 1, y = 0, width = 163, height = 150 },
				textureRect = { x = 167, y = 386, width = 163, height = 150 },
				spriteSourceSize = { width = 165, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player02@2x.png",
				spriteColorRect = { x = 1, y = 0, width = 163, height = 150 },
				textureRect = { x = 2, y = 842, width = 163, height = 150 },
				spriteSourceSize = { width = 165, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player03@2x.png",
				spriteColorRect = { x = 1, y = 0, width = 163, height = 150 },
				textureRect = { x = 2, y = 690, width = 163, height = 150 },
				spriteSourceSize = { width = 165, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player04@2x.png",
				spriteColorRect = { x = 1, y = 0, width = 163, height = 150 },
				textureRect = { x = 2, y = 538, width = 163, height = 150 },
				spriteSourceSize = { width = 165, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player05@2x.png",
				spriteColorRect = { x = 1, y = 0, width = 163, height = 150 },
				textureRect = { x = 2, y = 386, width = 163, height = 150 },
				spriteSourceSize = { width = 165, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shakeToStart@2x.png",
				spriteColorRect = { x = 97, y = 18, width = 292, height = 45 },
				textureRect = { x = 332, y = 386, width = 292, height = 45 },
				spriteSourceSize = { width = 480, height = 75 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "title@2x.png",
				spriteColorRect = { x = 17, y = 25, width = 934, height = 106 },
				textureRect = { x = 2, y = 2, width = 934, height = 106 },
				spriteSourceSize = { width = 960, height = 150 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

