-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c3d2e4ec10bad42306b4edda21ed2bcd$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "armStyle01@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 27 },
				textureRect = { x = 471, y = 169, width = 35, height = 27 },
				spriteSourceSize = { width = 35, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "armStyle02@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 27 },
				textureRect = { x = 471, y = 140, width = 35, height = 27 },
				spriteSourceSize = { width = 35, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "legStyle01@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 35 },
				textureRect = { x = 110, y = 461, width = 27, height = 35 },
				spriteSourceSize = { width = 27, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "legStyle02@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 35 },
				textureRect = { x = 110, y = 424, width = 27, height = 35 },
				spriteSourceSize = { width = 27, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "skull@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 106, height = 84 },
				textureRect = { x = 2, y = 424, width = 106, height = 84 },
				spriteSourceSize = { width = 106, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle01@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 138 },
				textureRect = { x = 259, y = 2, width = 118, height = 138 },
				spriteSourceSize = { width = 118, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle02@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 138 },
				textureRect = { x = 139, y = 2, width = 118, height = 138 },
				spriteSourceSize = { width = 118, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle03@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 138 },
				textureRect = { x = 2, y = 284, width = 118, height = 138 },
				spriteSourceSize = { width = 118, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle04@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 138 },
				textureRect = { x = 2, y = 144, width = 118, height = 138 },
				spriteSourceSize = { width = 118, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle05@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 136 },
				textureRect = { x = 379, y = 2, width = 118, height = 136 },
				spriteSourceSize = { width = 118, height = 136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torsoStyle06@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 118, height = 140 },
				textureRect = { x = 2, y = 2, width = 118, height = 140 },
				spriteSourceSize = { width = 118, height = 140 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "weakened@2x.png",
				spriteColorRect = { x = 14, y = 10, width = 90, height = 122 },
				textureRect = { x = 379, y = 140, width = 90, height = 122 },
				spriteSourceSize = { width = 120, height = 140 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

