-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:1067b3384a86851cecbcadca8b598544$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "playerNumber01.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 2, y = 106, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber02.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 54, y = 54, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber03.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 2, y = 54, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber04.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 54, y = 2, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber05.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				textureRect = { x = 2, y = 2, width = 50, height = 50 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

