-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:22a1fcf0ac5c5c642876c8842a6e0ce5$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "playerNumber01@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 410, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber02@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 308, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber03@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 206, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber04@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 104, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerNumber05@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				textureRect = { x = 2, y = 2, width = 100, height = 100 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

