-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:4d32366e13b7ca765599bafa6e993f0e$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "player01.png",
				spriteColorRect = { x = 2, y = 3, width = 122, height = 122 },
				textureRect = { x = 2, y = 250, width = 122, height = 122 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player02.png",
				spriteColorRect = { x = 2, y = 3, width = 122, height = 122 },
				textureRect = { x = 126, y = 126, width = 122, height = 122 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player03.png",
				spriteColorRect = { x = 2, y = 3, width = 122, height = 122 },
				textureRect = { x = 2, y = 126, width = 122, height = 122 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player04.png",
				spriteColorRect = { x = 2, y = 3, width = 122, height = 122 },
				textureRect = { x = 126, y = 2, width = 122, height = 122 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player05.png",
				spriteColorRect = { x = 2, y = 3, width = 122, height = 122 },
				textureRect = { x = 2, y = 2, width = 122, height = 122 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "skull.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 42 },
				textureRect = { x = 126, y = 250, width = 53, height = 42 },
				spriteSourceSize = { width = 53, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

