-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:13b96dbbed29fb2226b589ab7313fc5e$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "clock@2x.png",
				spriteColorRect = { x = 6, y = 6, width = 118, height = 118 },
				textureRect = { x = 2, y = 134, width = 118, height = 118 },
				spriteSourceSize = { width = 130, height = 130 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "textbox@2x.png",
				spriteColorRect = { x = 0, y = 0, width = 350, height = 130 },
				textureRect = { x = 2, y = 2, width = 350, height = 130 },
				spriteSourceSize = { width = 350, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

